#pragma once

// generated by tools/midi_to_chart_header.py
// source midi: charts/steves_lava_chicken/notes.mid
// difficulty: easy
// lane order: 0=hihat, 1=kick, 2=snare
// include this after a compatible chart note struct is available.

#ifndef AIR_DRUMS_CHART_NOTE_STRUCT
#define AIR_DRUMS_CHART_NOTE_STRUCT
struct AirDrumsChartNote {
  int time_ms;
  int lane;
};
#endif

constexpr int steves_lava_chicken_note_count = 71;
constexpr int steves_lava_chicken_song_end_ms = 32041;
constexpr AirDrumsChartNote steves_lava_chicken_notes[71] = {
  { 3051, 1 }, // kick
  { 3433, 2 }, // snare
  { 3814, 1 }, // kick
  { 4196, 2 }, // snare
  { 4577, 1 }, // kick
  { 4959, 2 }, // snare
  { 5340, 1 }, // kick
  { 5722, 2 }, // snare
  { 6103, 1 }, // kick
  { 6484, 2 }, // snare
  { 6866, 1 }, // kick
  { 7247, 2 }, // snare
  { 7629, 1 }, // kick
  { 8010, 2 }, // snare
  { 8392, 1 }, // kick
  { 8773, 2 }, // snare
  { 9154, 1 }, // kick
  { 9536, 2 }, // snare
  { 9917, 1 }, // kick
  { 10299, 2 }, // snare
  { 12587, 2 }, // snare
  { 12969, 1 }, // kick
  { 13350, 2 }, // snare
  { 13732, 1 }, // kick
  { 14113, 2 }, // snare
  { 14495, 1 }, // kick
  { 14876, 2 }, // snare
  { 15257, 1 }, // kick
  { 15639, 2 }, // snare
  { 16020, 1 }, // kick
  { 16402, 2 }, // snare
  { 16783, 1 }, // kick
  { 17165, 2 }, // snare
  { 17546, 1 }, // kick
  { 17928, 2 }, // snare
  { 18690, 2 }, // snare
  { 19072, 1 }, // kick
  { 19453, 2 }, // snare
  { 19835, 1 }, // kick
  { 20216, 2 }, // snare
  { 20598, 1 }, // kick
  { 20979, 2 }, // snare
  { 21360, 1 }, // kick
  { 21742, 2 }, // snare
  { 22123, 1 }, // kick
  { 22505, 2 }, // snare
  { 22886, 1 }, // kick
  { 23268, 2 }, // snare
  { 23649, 1 }, // kick
  { 24031, 2 }, // snare
  { 24412, 1 }, // kick
  { 24793, 2 }, // snare
  { 25175, 1 }, // kick
  { 25556, 2 }, // snare
  { 25938, 1 }, // kick
  { 26319, 2 }, // snare
  { 26701, 1 }, // kick
  { 27082, 2 }, // snare
  { 27463, 1 }, // kick
  { 27845, 2 }, // snare
  { 28226, 1 }, // kick
  { 28608, 2 }, // snare
  { 28989, 1 }, // kick
  { 29371, 2 }, // snare
  { 29752, 1 }, // kick
  { 30134, 2 }, // snare
  { 30515, 1 }, // kick
  { 30896, 2 }, // snare
  { 31278, 1 }, // kick
  { 31659, 2 }, // snare
  { 32041, 2 }, // snare
};
