#pragma once

// generated by tools/midi_to_chart_header.py
// source midi: charts/steves_lava_chicken/notes.mid
// difficulty: super_easy
// lane order: 0=hihat, 1=kick, 2=snare
// include this after a compatible chart note struct is available.

#ifndef AIR_DRUMS_CHART_NOTE_STRUCT
#define AIR_DRUMS_CHART_NOTE_STRUCT
struct AirDrumsChartNote {
  int time_ms;
  int lane;
};
#endif

constexpr int steves_lava_chicken_super_easy_note_count = 39;
constexpr int steves_lava_chicken_super_easy_song_end_ms = 32041;
constexpr AirDrumsChartNote steves_lava_chicken_super_easy_notes[39] = {
  { 3051, 1 }, // kick
  { 3814, 2 }, // snare
  { 4577, 1 }, // kick
  { 5340, 2 }, // snare
  { 6103, 1 }, // kick
  { 6866, 2 }, // snare
  { 7629, 1 }, // kick
  { 8392, 2 }, // snare
  { 9154, 1 }, // kick
  { 9917, 2 }, // snare
  { 10680, 1 }, // kick
  { 11443, 2 }, // snare
  { 12206, 1 }, // kick
  { 12969, 2 }, // snare
  { 13732, 1 }, // kick
  { 14495, 2 }, // snare
  { 15257, 1 }, // kick
  { 16020, 2 }, // snare
  { 16783, 1 }, // kick
  { 17546, 2 }, // snare
  { 18309, 1 }, // kick
  { 19072, 2 }, // snare
  { 19835, 1 }, // kick
  { 20598, 2 }, // snare
  { 21360, 1 }, // kick
  { 22123, 2 }, // snare
  { 22886, 1 }, // kick
  { 23649, 2 }, // snare
  { 24412, 1 }, // kick
  { 25175, 2 }, // snare
  { 25938, 1 }, // kick
  { 26701, 2 }, // snare
  { 27463, 1 }, // kick
  { 28226, 2 }, // snare
  { 28989, 1 }, // kick
  { 29752, 2 }, // snare
  { 30515, 1 }, // kick
  { 31278, 2 }, // snare
  { 32041, 1 }, // kick
};
