#pragma once

// generated by tools/midi_to_chart_header.py
// source midi: charts/takefive/notes.mid
// difficulty: easy
// lane order: 0=hihat, 1=kick, 2=snare
// include this after a compatible chart note struct is available.

#ifndef AIR_DRUMS_CHART_NOTE_STRUCT
#define AIR_DRUMS_CHART_NOTE_STRUCT
struct AirDrumsChartNote {
  int time_ms;
  int lane;
};
#endif

constexpr int takefive_note_count = 141;
constexpr int takefive_song_end_ms = 298237;
constexpr AirDrumsChartNote takefive_notes[141] = {
  { 22322, 2 }, // snare
  { 52547, 2 }, // snare
  { 54339, 2 }, // snare
  { 56143, 2 }, // snare
  { 63331, 2 }, // snare
  { 72339, 2 }, // snare
  { 83110, 2 }, // snare
  { 85603, 2 }, // snare
  { 106346, 2 }, // snare
  { 125735, 2 }, // snare
  { 128132, 2 }, // snare
  { 129167, 2 }, // snare
  { 130877, 2 }, // snare
  { 132566, 2 }, // snare
  { 134268, 2 }, // snare
  { 134941, 2 }, // snare
  { 135970, 2 }, // snare
  { 136995, 2 }, // snare
  { 137656, 2 }, // snare
  { 138326, 2 }, // snare
  { 138661, 1 }, // kick
  { 139375, 2 }, // snare
  { 140372, 1 }, // kick
  { 141047, 2 }, // snare
  { 141725, 2 }, // snare
  { 142751, 2 }, // snare
  { 143786, 2 }, // snare
  { 144460, 1 }, // kick
  { 145150, 1 }, // kick
  { 145487, 2 }, // snare
  { 146136, 2 }, // snare
  { 147802, 2 }, // snare
  { 148812, 2 }, // snare
  { 149504, 2 }, // snare
  { 151178, 2 }, // snare
  { 151859, 2 }, // snare
  { 153911, 1 }, // kick
  { 155282, 0 }, // hihat
  { 157317, 2 }, // snare
  { 158007, 2 }, // snare
  { 160748, 2 }, // snare
  { 161430, 2 }, // snare
  { 164234, 2 }, // snare
  { 164909, 2 }, // snare
  { 167734, 2 }, // snare
  { 168449, 2 }, // snare
  { 171225, 2 }, // snare
  { 171919, 2 }, // snare
  { 172620, 2 }, // snare
  { 174737, 2 }, // snare
  { 175459, 2 }, // snare
  { 176485, 1 }, // kick
  { 177557, 0 }, // hihat
  { 178293, 2 }, // snare
  { 178972, 2 }, // snare
  { 179656, 2 }, // snare
  { 180013, 1 }, // kick
  { 181070, 0 }, // hihat
  { 182319, 2 }, // snare
  { 184517, 0 }, // hihat
  { 184517, 2 }, // snare
  { 184861, 2 }, // snare
  { 185919, 2 }, // snare
  { 188015, 0 }, // hihat
  { 188755, 2 }, // snare
  { 189431, 0 }, // hihat
  { 189431, 2 }, // snare
  { 190134, 0 }, // hihat
  { 193249, 2 }, // snare
  { 194652, 0 }, // hihat
  { 197067, 0 }, // hihat
  { 198110, 2 }, // snare
  { 199128, 2 }, // snare
  { 202575, 1 }, // kick
  { 203281, 2 }, // snare
  { 203966, 2 }, // snare
  { 204309, 2 }, // snare
  { 205315, 0 }, // hihat
  { 206029, 1 }, // kick
  { 207377, 2 }, // snare
  { 207714, 0 }, // hihat
  { 208757, 2 }, // snare
  { 210142, 0 }, // hihat
  { 210142, 2 }, // snare
  { 210829, 2 }, // snare
  { 211172, 1 }, // kick
  { 212195, 2 }, // snare
  { 212887, 2 }, // snare
  { 215628, 2 }, // snare
  { 216342, 2 }, // snare
  { 217731, 0 }, // hihat
  { 218074, 0 }, // hihat
  { 219080, 2 }, // snare
  { 219764, 1 }, // kick
  { 221141, 0 }, // hihat
  { 222161, 2 }, // snare
  { 222828, 2 }, // snare
  { 223828, 0 }, // hihat
  { 225915, 2 }, // snare
  { 226597, 1 }, // kick
  { 227950, 2 }, // snare
  { 228289, 2 }, // snare
  { 228979, 2 }, // snare
  { 229997, 1 }, // kick
  { 231377, 2 }, // snare
  { 231726, 1 }, // kick
  { 232423, 1 }, // kick
  { 233389, 2 }, // snare
  { 234826, 2 }, // snare
  { 235172, 1 }, // kick
  { 235863, 2 }, // snare
  { 236890, 1 }, // kick
  { 238310, 2 }, // snare
  { 238663, 1 }, // kick
  { 239721, 1 }, // kick
  { 240427, 2 }, // snare
  { 241465, 2 }, // snare
  { 242836, 1 }, // kick
  { 244278, 2 }, // snare
  { 245301, 2 }, // snare
  { 245649, 1 }, // kick
  { 246684, 0 }, // hihat
  { 247374, 0 }, // hihat
  { 248714, 0 }, // hihat
  { 249055, 0 }, // hihat
  { 252131, 0 }, // hihat
  { 252464, 2 }, // snare
  { 254808, 2 }, // snare
  { 255830, 0 }, // hihat
  { 257523, 1 }, // kick
  { 258893, 0 }, // hihat
  { 259234, 2 }, // snare
  { 260945, 1 }, // kick
  { 263325, 2 }, // snare
  { 265079, 2 }, // snare
  { 265777, 0 }, // hihat
  { 266121, 0 }, // hihat
  { 266121, 2 }, // snare
  { 266821, 2 }, // snare
  { 269324, 0 }, // hihat
  { 298237, 2 }, // snare
};
