#!/usr/bin/env python3

from pathlib import Path
import re


try:
    Import("env")  # type: ignore[name-defined]
except NameError:
    env = None


if env is not None:
    REPO_ROOT = Path(env.subst("$PROJECT_DIR")).resolve()
else:
    REPO_ROOT = Path(__file__).resolve().parents[1]
GENERATED_CHARTS_DIR = REPO_ROOT / "src" / "generated_charts"
REGISTRY_PATH = GENERATED_CHARTS_DIR / "chart_registry.h"


CHART_HEADER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*_chart\.h$")


def chart_headers() -> list[Path]:
    if not GENERATED_CHARTS_DIR.exists():
        return []

    return sorted(
        path
        for path in GENERATED_CHARTS_DIR.glob("*_chart.h")
        if path.name != REGISTRY_PATH.name and CHART_HEADER_RE.match(path.name)
    )


def build_registry_text(headers: list[Path]) -> str:
    includes = []
    entries = []

    for header in headers:
        chart_id = header.name.removesuffix("_chart.h")
        includes.append(f'#include "{header.name}"')
        entries.append(
            f'  {{ "{chart_id}", {chart_id}_notes, {chart_id}_note_count, {chart_id}_song_end_ms }},'
        )

    include_text = "\n".join(includes)
    if entries:
        macro_lines = []
        for index, entry in enumerate(entries):
            suffix = " \\" if index < len(entries) - 1 else ""
            macro_lines.append(f"{entry}{suffix}")
        entry_text = "\n".join(macro_lines)
    else:
        entry_text = "  // No generated chart headers found."

    return f"""#pragma once

// Generated by tools/generate_chart_registry.py. Do not edit by hand.

{include_text}

#define AIR_DRUMS_SONG_CHARTS \\
{entry_text}
"""


def generate_chart_registry() -> None:
    GENERATED_CHARTS_DIR.mkdir(parents=True, exist_ok=True)
    new_text = build_registry_text(chart_headers())

    if REGISTRY_PATH.exists() and REGISTRY_PATH.read_text(encoding="utf-8") == new_text:
        return

    REGISTRY_PATH.write_text(new_text, encoding="utf-8")
    print(f"generated {REGISTRY_PATH.relative_to(REPO_ROOT).as_posix()}")


def before_build(source, target, env):  # noqa: ANN001
    generate_chart_registry()


if env is not None:
    generate_chart_registry()
    env.AddPreAction("buildprog", before_build)
elif __name__ == "__main__":
    generate_chart_registry()
